x-service-templates:
  payment-processor: &payment-processor
    image: zanfranceschi/payment-processor:amd64-20250807222453
    networks:
      - payment-processor
      - payment-processor-db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 10
        window: 5s
      resources:
        limits:
          cpus: "1.5"
          memory: "100MB"

  payment-processor-db: &payment-processor-db
    image: postgres:17-alpine
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096 -c synchronous_commit=0 -c fsync=0 -c full_page_writes=0
    networks:
      - payment-processor-db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rinha
    deploy:
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 10
        window: 5s
      resources:
        limits:
          cpus: "1.5"
          memory: "250MB"

  backend-service: &backend-service
    image: 4emcos/rinha-backend-2025-bun:1.0.16

    depends_on:
      - writer
    volumes:
      - socket_data:/tmp
    networks:
      - payment-processor
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "70MB"

services:
  backend-01:
    <<: *backend-service
    container_name: backend-01
    hostname: backend-01
    environment:
      APP_PORT: 5000
      PAYMENT_PROCESSOR_FALLBACK: http://payment-processor-fallback:8080
      PAYMENT_PROCESSOR_DEFAULT: http://payment-processor-default:8080
      WRITER_SOCKET_PATH: /tmp/writer.sock
      SERVICE_SOCKET_PATH: /tmp/backend_1.sock

  backend-02:
    <<: *backend-service
    container_name: backend-02
    hostname: backend-02
    environment:
      APP_PORT: 5000
      PAYMENT_PROCESSOR_FALLBACK: http://payment-processor-fallback:8080
      PAYMENT_PROCESSOR_DEFAULT: http://payment-processor-default:8080
      WRITER_SOCKET_PATH: /tmp/writer.sock
      SERVICE_SOCKET_PATH: /tmp/backend_2.sock

  writer:
    hostname: writer
    image: 4emcos/writer:2.0.4
    environment:
      - DATABASE_SOCKET_PATH=/tmp/writer.sock
      - GOGC=100
      - GOMAXPROCS=1
      - GODEBUG=gctrace=0
    volumes:
      - socket_data:/tmp
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "70MB"

  # load balance using in specific submission
  #  load-balance:
  #    image: openresty/openresty:bullseye
  #    volumes:
  #      - ./devops/nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
  #      - ./devops/nginx/handle_requests.lua:/usr/local/openresty/nginx/lua/handle_requests.lua:ro
  #      - socket_data:/tmp
  #    depends_on:
  #      - backend-01
  #      - backend-02
  #    networks:
  #      - backend
  #    ports:
  #      - '9999:80'
  #    deploy:
  #      resources:
  #        limits:
  #          cpus: "0.5"
  #          memory: "75MB"

  load-balance-go:
    image: 4emcos/load-balance:1.0.3
    volumes:
      - socket_data:/tmp
    depends_on:
      - backend-01
      - backend-02
    networks:
      - backend
    ports:
      - '9999:9999'
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "95MB"


  payment-processor-1:
    <<: *payment-processor
    container_name: payment-processor-default
    hostname: payment-processor-default
    environment:
      - TRANSACTION_FEE=0.05
      - RATE_LIMIT_SECONDS=5
      - INITIAL_TOKEN=123
      - DB_CONNECTION_STRING=Host=/var/run/postgresql;Port=5432;Database=rinha;Username=postgres;Password=postgres;Minimum Pool Size=15;Maximum Pool Size=20;Connection Pruning Interval=3
    ports:
      - 8001:8080
    volumes:
      - postgres-socket-01:/var/run/postgresql
    depends_on:
      - payment-processor-db-1

  payment-processor-db-1:
    <<: *payment-processor-db
    container_name: payment-processor-default-db
    hostname: payment-processor-default-db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-socket-01:/var/run/postgresql

  payment-processor-2:
    <<: *payment-processor
    container_name: payment-processor-fallback
    hostname: payment-processor-fallback
    environment:
      - TRANSACTION_FEE=0.15
      - RATE_LIMIT_SECONDS=5
      - INITIAL_TOKEN=123
      - DB_CONNECTION_STRING=Host=/var/run/postgresql;Port=5432;Database=rinha;Username=postgres;Password=postgres;Minimum Pool Size=15;Maximum Pool Size=20;Connection Pruning Interval=3
    ports:
      - 8002:8080
    volumes:
      - postgres-socket-02:/var/run/postgresql
    depends_on:
      - payment-processor-db-2

  payment-processor-db-2:
    <<: *payment-processor-db
    container_name: payment-processor-fallback-db
    hostname: payment-processor-fallback-db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-socket-02:/var/run/postgresql

volumes:
  socket_data:
  postgres-socket-01:
  postgres-socket-02:

networks:
  payment-processor:
    name: payment-processor
    driver: bridge
  payment-processor-db:
    driver: bridge
  backend:
    driver: bridge
