export const CONFIG = {
  BATCH_SIZE: 50,
  MIN_WAIT_TIME: 1,
  MAX_WAIT_TIME: 10,
  MAX_RETRY_DELAY: 1,
  CONCURRENT_REQUESTS: 100,
  QUEUE_DRAIN_THRESHOLD: 50,
  MAX_QUEUE_SIZE: 20000,
  RETRY_BACKOFF_MULTIPLIER: 1.2
} as const
